name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: '.nvmrc'

    - name: Install turbo
      shell: bash
      run: npm i -g turbo

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      name: pnpm-cache
      id: pnpm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Cache TypeScript TSBuild Info Files
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: '*/*/node_modules/.cache/tsbuildinfo.json'
        # Commit hash is for working around this: https://github.com/actions/cache/issues/106
        key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

    - name: pnpm
      shell: bash
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline
