query contentQuery($relativePath: String!) {
	page(relativePath: $relativePath) {
		...PageParts
		_sys {
			relativePath
			breadcrumbs
			filename
		}
	}

	workConnection(sort: "date", last: -1) {
		edges {
			node {
				...WorkParts
				id
				_sys {
					filename
					basename
					breadcrumbs
					path
					relativePath
					extension
				}
			}
		}
	}

	productConnection {
		edges {
			node {
				...ProductParts
				id
				_sys {
					filename
					basename
					breadcrumbs
					path
					relativePath
					extension
				}
			}
		}
	}
}

query workQuery($relativePath: String!) {
	work(relativePath: $relativePath) {
		...WorkParts
		_sys {
			relativePath
			breadcrumbs
		}
	}
}

query sitemapQuery {
	pageConnection {
		edges {
			node {
				title
				id
				_sys {
					filename
					breadcrumbs
				}
			}
		}
	}

	workConnection {
		edges {
			node {
				title
				id
				date
				category
				_sys {
					filename
					breadcrumbs
				}
			}
		}
	}
}

query globalQuery($relativePath: String!) {
	global(relativePath: $relativePath) {
		...GlobalParts
	}
}
