query contentQuery($relativePath: String!) {
	page(relativePath: $relativePath) {
		...PageParts
		_sys {
			relativePath
			breadcrumbs
			filename
		}
	}
}

query sitemapQuery {
	pageConnection {
		edges {
			node {
				title
				id
				_sys {
					filename
					breadcrumbs
				}
			}
		}
	}
}
