query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
  blogConnection(sort: "date", last: -1) {
    edges {
      node {
        ...BlogParts
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
      }
    }
  }
  wikiConnection(sort: "date", last: -1) {
    edges {
      node {
        ...WikiParts
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
      }
    }
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  blog(relativePath: $relativePath) {
    ...BlogParts
  }
  blogConnection(sort: "date", last: -1) {
    edges {
      node {
        ...BlogParts
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
      }
    }
  }
}

query wikiQuery($relativePath: String!) {
  ...LayoutQueryFragment
  wiki(relativePath: $relativePath) {
    ...WikiParts
  }
}
