fragment BlogParts on Blog {
  seo {
    __typename
    title
    description
    canonical
    seoImg
    partialSeoImage
    cardType
  }
  title
  tags
  category
  heroImg
  excerpt
  date
  body
}

fragment GlobalParts on Global {
  navigation {
    __typename
    main {
      __typename
      href
      label
      isButton
    }
    actions {
      __typename
      href
      label
      isButton
    }
  }
  social {
    __typename
    facebook
    twitter
    instagram
    github
  }
  paths {
    __typename
    wiki
    blog
    contact
  }
  companyInfo {
    __typename
    companyName
    vat
  }
}

fragment PageParts on Page {
  seo {
    __typename
    title
    description
    canonical
    seoImg
    partialSeoImage
    cardType
  }
  title
  blocks {
    __typename
    ... on PageBlocksBigTitle {
      title
      action {
        __typename
        title
        label
        href
      }
    }
    ... on PageBlocksBlog {
      header {
        __typename
        title
        subtitle
        link
        image
      }
      searchEnabled
      featuredEnabled
      tags
      count
    }
    ... on PageBlocksContent {
      body
    }
    ... on PageBlocksFeatures {
      title
      subTitle
      items {
        __typename
        title
        description
        icon
      }
    }
    ... on PageBlocksHero {
      title
      text
      image {
        __typename
        src
        alt
      }
    }
    ... on PageBlocksKeywordList {
      title
      keywords
    }
    ... on PageBlocksWiki {
      header {
        __typename
        title
        subtitle
        link
        image
      }
      searchEnabled
      tags
      count
    }
    ... on PageBlocksProducts {
      header {
        __typename
        title
        subtitle
        link
      }
      tags
      count
    }
  }
}

fragment ProductParts on Product {
  title
  description
  link
  soon
  image
  tags
}

fragment TagsParts on Tags {
  title
}

fragment WikiParts on Wiki {
  seo {
    __typename
    title
    description
    canonical
    seoImg
    partialSeoImage
    cardType
  }
  title
  tags
  excerpt
  date
  body
}
